version: '3.8'

services:
  app:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: chebryakov
      POSTGRES_PASSWORD: password
      POSTGRES_DB: RestApiServer

    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: